### ISSUE TITLE
Feature - Add slider/toggle for allowing additional bots.

### ISSUE THREAD

**Issue by polarathene** [polarathene/biglobby#12]
Some players want to fill unused slots with bots and resort to editing code themselves or other mods. BigLobby can handle this with settings support.

**Comment by antonpup** [comment]
Will this include difficulty scaling based on player count? We can have a points system where with enough players/bots it will gradually activate new tiers of difficulty. And this system will only activate once the player/bot count in-game is over 4. For example if a player adds 1.0 points and a bot adds 0.5 or 0.75 points, we can have following tiers.

Default Difficulty starting points:
Easy - 0
Normal - 2
Hard - 4
Overkill - 6
Deathwish - 8
(Pro modifier multiplies the difficulty score by 1.25, so 25% more)

From thereon out, if there are more than 4 players or additional bots are enabled, the linear curve goes like so:
`( "Lobby Difficulty" + ( "bot count" * 0.75 ) + ( ( "player count" - 4 ) * 0.75 ) ) * ( "is deathwish" == true ? 1.25 : 1 )`

This score can be used throughout the game to modify the amount of spawned enemies, the rng (in terms of map generation and computer hacking for example), and boost frequency of negative in-game events (like frequency of the beast breaking on big bank).

**Comment by polarathene** [comment]
@antonpup If you'd like to contribute code for that feature you're more than welcome to. If at all possible adding an existing difficulty mod as a dependency for BLT to pull in and use is better for us(someone else maintains it, assuming it's quite a bit of code). If they don't have support for scaling with a value like you suggest, try to add it in `_custom` folder, else set it in BigLobbyGlobals.

**Comment by polarathene** [comment]
Added in [v2.30](https://github.com/polarathene/biglobby/commit/e63c3b12ecb0259b8c48423e5334dc4f66c4fd54) commit  fa87b11aa8244a352cc21e3b43118c6803a1867c
