### ISSUE TITLE
Can't join each other, Crash to Desktop on Join

### ISSUE THREAD

**Issue by mastermast** [polarathene/biglobby#20]
As soon as I join a friend or he joins me, the host crashes
Crash date: 09.09.2016 15:08:14

PAYDAY 2 Crash log
Application has crashed: C++ exception
...ib/network/base/session_states/_hoststateinlobby.lua:13: attempt to index local 'sender' (a nil value)
## SCRIPT STACK

Callstack:
         payday2_win32_release  (???)     ???  
         payday2_win32_release  (???)     ???                                                 
## Current thread: Main

System information:
    Application version : 1.54.12
    CPU : AMD FX(tm)-4300 Quad-Core Processor (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
    DirectX : 10.0 
    GPU : NVIDIA GeForce GTX 750 / nvd3dum.dll[10.18.13.6881]
    Language : @IDb6ce5cf32130deac@
    Memory :     412014    0MB
    OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
    Physics : threaded
    Renderer : DX9 threaded
    Sound : Razer Inc. (Kopfhörer (Razer Kraken 7.1 Chroma))

So yea, I would be very thankful for any responses

I also have the following mods installed:
base
BeardLib
biglobby
ChatCommand
CompactHUD
DLCUlocker
downloads
GoonMod
logs
PocoHud3
saves
Spawn Faster

**Comment by polarathene** [comment]
Were you using it before successfully? How long ago was that if that's the case and when did the latest update come out? Chances are some new network code needs support or was changed.

**Comment by mastermast** [comment]
I was using the 1.0 a long time ago as far as i know, that has worked just fine.

**Comment by polarathene** [comment]
Yes, the mod worked for a while and had updates. Last few months I've not been able to find time to update it. One of the other collaborators may be able to help, otherwise I'll try release an update by the end of the month.

If you're not aware, the mod is not that popular anymore, some maps have code that needs quite a bit of time/effort to look into to test/fix(always been the case), and usually every update(about 2 weeks) from Overkill breaks the mod. It's really only useful if you want to arrange a game with 5+ friends as it's rare someone else will join.

**Comment by Ciberzak** [comment]
It is a great mod !!!!
Huy u.u y justo que empezamos a jugar con amigos usando este mod . Podemos ayudar de alguna forma ?

**Comment by polarathene** [comment]
@Ciberzak thanks, I appreciate it :)

> Huy u.u y justo que empezamos a jugar con amigos usando este mod . Podemos ayudar de alguna forma ?

I can't commit much time to this mod development right now as I need to find myself a new job :(

If you want to see the mod fixed sooner, I need the latest `network.network_settings` file. To get this file, you need to use the `Bundle Modder` tool and extract assets. I have listed the steps [here](https://github.com/polarathene/biglobby/issues/18#issuecomment-230069589), another developer should be able to do this easy too. If you can provide the file for me I will put out an update, I can't test it... so it may not work if more changes are needed.

**Comment by Ciberzak** [comment]
Disculpa si no entiendo mucho , mi ingles no es muy bueno ya que nunca había tenido una buena base de ingles voy a ver que puedo hacer. Y gracias !

**Comment by mastermast** [comment]
@polarthene take your time, don't rush it. As long as it works at some point its fine!
Also I love your work :3

**Comment by Ciberzak** [comment]
Could you explain me how to do that much is not , so we can help you please?

**Comment by SnackDash** [comment]
Could you explain me how to do that much is not , so we can help you please?

**Comment by polarathene** [comment]
@SnackDash My [last reply](https://github.com/polarathene/biglobby/issues/20#issuecomment-246115783) explains how to do normal fix. You can provide me this `network.network_settings` file and I will handle rest for you. Otherwise ask me any question and I will answer.

**Comment by Ciberzak** [comment]
¿Les molesta si les pedimos algunas capturas de pantalla de que hay que hacer exactamente con el Bundle Modder ? Es que hace días ando probando y todavía no encuentro la forma 
Desde ya gracias saludos y perdón las molestias !

**Comment by CudaFrenzi** [comment]
@polarathene Hello, I got the file you need here.
[U107network.network.settings.zip](https://github.com/polarathene/biglobby/files/473427/U107network.network.settings.zip)

**Comment by Ciberzak** [comment]
Muchisimas gracias ! 
De verdad estamos/estoy muy agradecido y perdón si no pudimos ayudar en mucho

**Comment by polarathene** [comment]
@CudaFrenzi Thanks, I will update the pdmod with this file. I need to do a few other tasks as well before the update is released, it should be ready in a few hours time, I will post again with a link once ready :)

@Ciberzak Screenshots for Bundle Modder update steps is good suggestion! I will look into making an update guide with screenshots after I make release :)

**Comment by polarathene** [comment]
It turns out I still need the game files to make this pdmod. It will take me a while to download the game again, I have all other changes ready to go and will make the pdmod file once I have the game. In meantime if you know how to make pdmod from instructions I linked, I have file attached. Will update again when release is published :)

[pdmod src.zip](https://github.com/polarathene/biglobby/files/473959/pdmod.src.zip)

**Comment by thecrimsondragon** [comment]
great to hear that i normaly use big lobby to play with streamers and do overdrill with them its cool and kinda funny

**Comment by polarathene** [comment]
Hey guys thanks for your patience :)

I've released [new version here](https://github.com/polarathene/biglobby/releases/tag/v2.28), at the bottom download the file [`biglobby_v2.28.zip`](https://github.com/polarathene/biglobby/releases/download/v2.28/biglobby_v2.28.zip). 

Let me know if it causes any problems.
