### ISSUE TITLE
Can't join each other, Crash to Desktop on Join [a PS]

### ISSUE THREAD

**Issue by mastermast** [polarathene/biglobby#21]
Hey Bud, me again, just wanted to say that the last fix didn't work for us 2, if my buddy connects to me then I crash, when I connect to him then I can't connect overall and he get's the message "Authentification failed" as soon as I join.
It may have to do with the fact that the lobby is being treated incorrectly

Just wanted to let ya know, I'm open for any questions to the crash reports.

**Comment by polarathene** [comment]
Can you verify that you are both using the latest BLT lua mod that was released(2.28) and both installed the 2.28 pdmod?

I have added you to Steam.

**Comment by polarathene** [comment]
Error was due to using older pdmod. The pdmod file now has version viewable in Bundle Modder to avoid confusion.
