### ISSUE TITLE
Newest update has broken the mod, anyway I can help?

### ISSUE THREAD

**Issue by demowulf** [polarathene/biglobby#22]
I read that I can extract a network file from my assets folder in the payday 2 directory, after that's done what else do I need to do? The instructions were a bit unclear. Or can I just upload it here for it to be looked at? We have like 8 people trying to play Payday 2 and its sad that we can't get a lobby anymore.

**Comment by polarathene** [comment]
Yeah sorry about that, I don't think I've gotten around to adding an official guide yet. I'll be able to handle the patch to get it working again for you shortly if it doesn't require any other changes :)

**Comment by polarathene** [comment]
@demowulf You can download the new release zip [here](https://github.com/polarathene/biglobby/releases/tag/v2.29), let me know if you run into any problems :)

**Comment by demowulf** [comment]
Thank you so much! We'll be trying it later today, I'll let you know. This means a lot to me!
