### ISSUE TITLE
Crash when shooting

### ISSUE THREAD

**Issue by Elkurr** [polarathene/biglobby#23]
Hey, been having a recent issue when my friends and I can all join the lobby and enter game, but as soon as anyone fires their gun we all crash. Will upload crash report as soon as I get home if needed.

**Comment by polarathene** [comment]
No need at present. I haven't synced to the latest update, new network functions will likely be the cause. I could update it but CrimeFest with it's regular updates will probably break it each time..

**Comment by Elkurr** [comment]
I see, that makes sense, thanks for your response

**Comment by polarathene** [comment]
@Elkurr I've updated the mod to the latest game update, you can find the .zip on the releases page [here](https://github.com/polarathene/biglobby/releases/tag/v2.30). Thank you for your patience :)
