### ISSUE TITLE
Biglobby Payday 2 Version 2.30 crash

### ISSUE THREAD

**Issue by pangeranpas** [polarathene/biglobby#24]

**Comment by polarathene** [comment]
I'd love to help you, but without a crashlog or any other information like what you were doing I can't replicate that to fix it.

**Comment by pangeranpas** [comment]
Here sir
[2016_10_21_log.txt](https://github.com/polarathene/biglobby/files/543407/2016_10_21_log.txt)

**Comment by polarathene** [comment]
@pangeranpas thanks for that, I see my mistake and have fixed it. You'll want version [v2.31](https://github.com/polarathene/biglobby/releases/tag/v2.31), you only need to update the BLT mod, pdmod is fine.

**Comment by pangeranpas** [comment]
@polarathene Thanks sir, keep a great work 👍
