### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by flaithz** [polarathene/biglobby#25]
i've been update to the latest version , but it keep crashing, i try to verify, uninstall the old mod, reinstall the latest mod, but nothing change

my crash log http://pastebin.com/Myu7sRHJ

thankyou

**Comment by polarathene** [comment]
Thanks for the log, looking into it now :)

**Comment by polarathene** [comment]
Fixed with version [v2.31](https://github.com/polarathene/biglobby/releases/tag/v2.31), you only need to update the BLT mod, pdmod is fine. Thanks for the report!
