### ISSUE TITLE
Update to Support 1.56.0

### ISSUE THREAD

**Issue by Adam395** [polarathene/biglobby#26]
With the end of Hoxtober, please update to support 1.56.0. Attempt to create an 8 person lobby resulted in repeated crash-on-join and crash-on-shoot errors for all players, including host.

**Comment by polarathene** [comment]
@Adam395 What version of BigLobby are you using? Is it the latest release from today?(U119/1.56.0 support) Everyone should be using the latest BLT mod and pdmod from the v2.31 zip file.

**Comment by polarathene** [comment]
Oh I think I see the problem, did you end up downloading t[his release from June](https://github.com/polarathene/biglobby/releases/tag/v2.0.0-alpha)? I just noticed it is on the main page in the instructions. I'll update that as well, you can find the latest release [here](https://github.com/polarathene/biglobby/releases/tag/v2.31)

**Comment by polarathene** [comment]
Thanks for the bug report, the README has been updated with proper links now, no longer locked to old versions :) There was a change in versioning scheme and I forgot to reflect that with the README links. I'm able to host BigLobby and start a game firing my weapon, I'm pretty sure you're just on an older version, if not let me know and I'll fix it :)
