### ISSUE TITLE
Sentry Gun Crash

### ISSUE THREAD

**Issue by Shad0wlife** [polarathene/biglobby#27]
Me and a friend just played around with big lobby and better bots. When a sentry gun was placed, the game crashed for both of us. The problem probably comes from big lobby since it's the only on4e I could pinpoint in the crashlog:

Current thread: Main
Script stack:
                        send()  lib/network/base/networkpeer.lua:1018  
                        send()  @mods/biglobby/lua/lib/network/base/_networkpeer.lua:14  
                _send_queued()  lib/network/base/networkpeer.lua:1056  
            send_queued_sync()  lib/network/base/networkpeer.lua:1078  
       send_to_peers_synched()  lib/network/base/basenetworksession.lua:687  
                        send()  lib/network/base/extensions/networkbaseextension.lua:11  
               damage_bullet()  lib/units/enemies/cop/copdamage.lua:550  
          give_impact_damage()  lib/units/weapons/raycastweaponbase.lua:1636  
                on_collision()  lib/units/weapons/raycastweaponbase.lua:1567  
               _fire_raycast()  lib/units/weapons/sentrygunweapon.lua:338  
                        fire()  lib/units/weapons/sentrygunweapon.lua:288  
                trigger_held()  lib/units/weapons/sentrygunweapon.lua:251  
                   _upd_fire()  lib/units/equipment/sentry_gun/sentrygunbrain.lua:492  
                                lib/units/equipment/sentry_gun/sentrygunbrain.lua:56

I'm playing on game version v1.56.60 (should be Update 119.1).

**Comment by polarathene** [comment]
What are the BigLobby BLT and PDmod versions you're using?

**Comment by polarathene** [comment]
Found the sentry related bug. It was due to @simon-wh [commit](https://github.com/polarathene/biglobby/commit/f6f211b6f28662580495986a0fbce104cf8259a7#diff-a823b9734566cd2fd1ced4c85b72d4e9R1012) only updating the original network method and not the BigLobby one as well. Fixed and released as [v2.32](https://github.com/polarathene/biglobby/releases/tag/v2.32) :)
