### ISSUE TITLE
Issue with 4 stores contract

### ISSUE THREAD

**Issue by sbrobecker** [polarathene/biglobby#28]
Hello,

Thanks for your work and this awesome mod. We spotted an issue after upgrading our payday client to last version (109.1) and biggerlobby to 2.32 version. 
When we try (even alone) to create a 4 stores lobby, game immediately crash in Netcrime.net screen (when you see windows 'creating lobby'). We updated betterbot at version 3.8 (to eventually correct an issue with biker heist), same result. When we test without biggerlobby mod and pdmod applied, no issue. 

Crashlogs have been verified and i cant spot errors who could explain this behavior.

Tested without betterbots to be sure, game crashes anyways as long as biggerlobby mod is activated.

I know it is not quite the most important heist, but always nice to have all game working fine.

Thanks.

**Comment by polarathene** [comment]
Could you please supply crashlog text file and the blt log file? They should point out why it crashed or show some errors.

**Comment by polarathene** [comment]
@sbrobecker I looked into it and was able to find out why and fix it for you. Please try [v2.33](https://github.com/polarathene/biglobby/releases/tag/v2.33), no changes to pdmod, v2.32 of pdmod is fine.

**Comment by polarathene** [comment]
I just noticed that my extra bots feature wasn't properly added. You can wait until the next version release or go to the [main page](https://github.com/polarathene/biglobby) and on top right click the green button to download master branch. You might be manually changing a line to enable more bots, this is no longer required, you get a slider for how many bots you'd like in the mod settings now :)

**Comment by sbrobecker** [comment]
Hello, thanks for this quick correction , however there where an issue with _achievementmanager.lua file, for information i had this error spotted in blt logs: 
**07:02:49 PM FATAL ERROR: mods/biglobby/lua/lib/managers/_achievementmanager.lua
07:02:49 PM FATAL ERROR: mods/biglobby/lua/lib/managers/_achievementmanager.lua:4: '}' expected (to close '{' at line 2) near '_give_reward'
07:02:49 PM FATAL ERROR: mods/biglobby/lua/lib/managers/_achievementmanager.lua
07:02:49 PM FATAL ERROR: attempt to call a string value**

I modified back concerned section to restore it like previous update , so replacing : (line 2 to 8)
**local orig__AchievmentManager = {
    award               = AchievmentManager.award
    _give_reward        = AchievmentManager._give_reward
    award_progress      = AchievmentManager.award_progress
    award_steam         = AchievmentManager.award_steam
    steam_unlock_result = AchievmentManager.steam_unlock_result
}**

With

**local orig__AchievmentManager = {}
orig__AchievmentManager.award = AchievmentManager.award
orig__AchievmentManager._give_reward = AchievmentManager._give_reward
orig__AchievmentManager.award_progress = AchievmentManager.award_progress
orig__AchievmentManager.award_steam = AchievmentManager.award_steam
orig__AchievmentManager.steam_unlock_result = AchievmentManager.steam_unlock_result**

And now 4 stores heists is up and running with biggerlobbies and multiplayer. 

Regards.

**Comment by polarathene** [comment]
Ah, late night coding errors :P Each line shouold have had a `,` inside the `{}` except the last one. Glad you got it working :)
