### ISSUE TITLE
[string "lib/managers/menu/menulobbyrenderer.lua"]:166: attempt to index local 'slot' (a nil value)

### ISSUE THREAD

**Issue by Aphyxia** [polarathene/biglobby#30]
Getting this error when a lobby of 5 people is going from lobby to briefing:
[string "lib/managers/menu/menulobbyrenderer.lua"]:166: attempt to index local 'slot' (a nil value)

If under 5 players, everything is fine. All of us have the same setup.

Crashlog:
https://www.dropbox.com/s/3rgqv8wno5svjjg/payday2_win32_release_2117156_crash_2016_11_4T19_36_58C0.mdmp?dl=0

Our mods: https://gyazo.com/d1dbf09f51118a7f6c101b44629e2701

**Comment by polarathene** [comment]
Hi, haven't had time to work on biglobby to fix this yet, please try [this workaround](https://github.com/polarathene/biglobby/issues/29#issuecomment-257302122)

**Comment by polarathene** [comment]
Closing as no response. This should be fixed with upcoming 2.35 bugfix.
