### ISSUE TITLE
Crash to Desktop When Starting Up the Game

### ISSUE THREAD

**Issue by SomeOrdinaryStudent** [polarathene/biglobby#31]
Whenever I try and start Payday 2 up with this mod installed, it automatically boots me back to the desktop.  I can't even get to the title screen.  I've installed the mod correctly, so is this a because of recent update, or am I doing something wrong?

**Comment by polarathene** [comment]
I haven't had time for modding on PD2 for some time. I can try push out an update for you but need more information. 

> because of recent update

Can you share a crashlog(text file in app data for the game) and/or your BLT log(game folder mods/log)? From the sounds of it the BLT log might be enough, an update probably changed code or added new network methods(normally this one).

> am I doing something wrong?

Following the instructions on the [main page](https://github.com/polarathene/biglobby#how-to-install) is all you should have to do to get it working right. If you have never used a BLT mod or pdmod mod before, there's a chance you might have done something wrong.

**Comment by SomeOrdinaryStudent** [comment]
Here's the BLT log
[2016_12_29_log.txt](https://github.com/polarathene/biglobby/files/676783/2016_12_29_log.txt)
Here's the Crash log
[crashlog.txt](https://github.com/polarathene/biglobby/files/676786/crashlog.txt)

**Comment by polarathene** [comment]
This error log does point out something being wrong, but then there are other errors unrelated to biglobby and the crash did not happen until after BotWeapons. Can you confirm if BigLobby works when it's the only mod in use? Or can you still not get passed the loading screen?

```
02:02:24 AM FATAL ERROR: mods/biglobby/lua/_custom/biglobby_globals.lua
02:02:24 AM FATAL ERROR: mods/base/req/json.lua:366: Unexpected character at Line 1 character 1: 
02:02:24 AM FATAL ERROR: mods/Music Module/CoreSetup.lua
02:02:24 AM FATAL ERROR: attempt to call a string value
02:02:25 AM Lua: [BotWeapons] Setting up weapons
02:02:25 AM Lua: [BotWeapons] Setting up weapon presets
02:02:30 AM Log: CURL CLOSED
```
The other log does indicate crash was due to BigLobby with:

```
Application has crashed: C++ exception
mods/biglobby/lua/lib/tweak_data/_moneytweakdata.lua:6: attempt to call method 'num_player_slots' (a nil value)
```
That method should exist and work, I am wondering if another mod you have is interfering with `mods/biglobby/lua/_custom/biglobby_globals.lua`.

**Comment by SomeOrdinaryStudent** [comment]
Big Lobby still did not work even after I tried running only this mod with Payday 2.  Here's the logs I did with those attempts if that helps.
[2016_12_29_log.txt](https://github.com/polarathene/biglobby/files/678223/2016_12_29_log.txt)
[crashlog.txt](https://github.com/polarathene/biglobby/files/678222/crashlog.txt)

**Comment by polarathene** [comment]
You still have this JSON error with BLT, I'm not sure why but maybe it is something wrong with your BLT install(`mods/base/req/json.lua:366`)? The game works fine with all your other mods? It would be good if someone else chimed in about it not working for them as well.

```
09:44:54 PM FATAL ERROR: mods/biglobby/lua/_custom/biglobby_globals.lua
09:44:54 PM FATAL ERROR: mods/base/req/json.lua:366: Unexpected character at Line 1 character 1: 
09:44:57 PM Log: CURL CLOSED
```
I'll try to update the game and look into it within the next few days.

**Comment by SomeOrdinaryStudent** [comment]
Okay, so apparently I tried this with previous versions of BLT and it lets kinda works, but I can only access the menu and doesn't load my other lua mods (crashes when I try to access them).
Here's the updated files
[crashlog.txt](https://github.com/polarathene/biglobby/files/679993/crashlog.txt)
[2017_01_01_log.txt](https://github.com/polarathene/biglobby/files/679994/2017_01_01_log.txt)

**Comment by polarathene** [comment]
Doesn't appear to be anything helpful/different in those logs from the original ones unfortunately. The BLT JSON error is odd, I looked at the Github code for it and it has not changed for over 6 months. 

Have you ever had BigLobby work for you in the past or is this first time trying the mod? Also can you confirm you are using the latest version of BigLobby? It should be 2.36 from [here](https://github.com/polarathene/biglobby/releases/tag/v2.36).

You could try this, open the file `mods/biglobby/lua/lib/tweak_data/_moneytweakdata.lua` in a text editor like Notepad. And change this line:

```
self.alive_humans_multiplier = self._create_value_table(1, self.alive_players_max, BigLobbyGlobals:num_player_slots(), false, 1)
```

To this:

```
self.alive_humans_multiplier = self._create_value_table(1, self.alive_players_max, BigLobbyGlobals:num_player_slots() or 4, false, 1)
```

It should prevent the crash error, not sure if it will fix things though.

**Comment by SomeOrdinaryStudent** [comment]
Yes, I have had BigLobby working on my computer before.  I downloaded the 2.36 of BigLobby and it still didn't work.  When I tried the fix, it brought me to the loading screen and then crashed. Apparently, it has something to do with a nil value in some of the files (according to the crashlog). I got curious and used the fix on some the applicable files and it kinda worked.  With the fixes that I could make, I was able to access the menus, but could't join any games without crashing.
Here's the logs
[2017_01_03_log.txt](https://github.com/polarathene/biglobby/files/682394/2017_01_03_log.txt)
[crashlog.txt](https://github.com/polarathene/biglobby/files/682395/crashlog.txt)
The files that I made fixes to were the files in the crashlog that had nil values and I just added  **or 4** to them.

**Comment by polarathene** [comment]
Thanks for that, some error look like you made typo breaking the lua file. But this shows that the extra progress seem to indicate problem is with the biglobby_globals file. I don't think any of the functions it has are being called by the other file for some reason(nil instead).

I will look into this in next few days, I've updated the game but can't play it just yet with my current hardware setup. It is very odd.

**Comment by polarathene** [comment]
@munyoop3 Hello sorry for the delay, please try [v2.37](https://github.com/polarathene/biglobby/releases/tag/v2.37). It's just a method update, but might be enough for you, when I'm able to to get the game running on my system again I'll try to assist more if needed.

**Comment by polarathene** [comment]
Closing. Mod should work fine and be up to date.
