### ISSUE TITLE
Unable to load any heist with BigLobby installed

### ISSUE THREAD

**Issue by RykahKnight** [polarathene/biglobby#32]
As soon as I load into a heist with this mod enabled (right when the black screen would start fading), my game crashes, and the log spits this out every time:

http://pastebin.com/q8BN9fQA

I've tried verifying my game files, trying both with and without other mods, I've tried with and without bots, and I've tried both being and not being the host, but STILL no dice.

**Comment by polarathene** [comment]
Thanks for the bug report. Looks like it could be due to an update, it's been a while since I sync'd. I'm unable to run the game myself at present but I'll try update all the network functions and push that as an update. Should hopefully fix things :)

**Comment by polarathene** [comment]
@RaraFolf Please try out [v2.37](https://github.com/polarathene/biglobby/releases/tag/v2.37) and let me know if it works for you :)

**Comment by polarathene** [comment]
Closing. Everything seems to work fine now.
