### ISSUE TITLE
Game crashing when players joining lobby

### ISSUE THREAD

**Issue by ProfessorShroom** [polarathene/biglobby#34]
We both have the mod installed but when they try to join my lobby my game will crash and their game will say failed to join.

**Comment by polarathene** [comment]
I need more debug information:

- BLT log and crashlog are helpful here. 
- Did the game update recently?
- What version of the BLT mod and pdmod are you using? It's important everyone uses the same versions and have both mods active.

I might have some time today to test with you if you can provide your steam name, I'll add you. There is no `TheJumpyWizard` apparently, and lots of `JumpyWizard`. You can add me `Pola` from New Zealand with the polar bear avatar.

**Comment by ProfessorShroom** [comment]
Here's the log: https://files.deanpcmad.com/2017/2017_01_25_log.txt 

I've added you.

**Comment by polarathene** [comment]
@TheJumpyWizard Any chance providing that crashlog as well please?

**Comment by ProfessorShroom** [comment]
Here you go: https://files.deanpcmad.com/2017/crashlog.txt

**Comment by polarathene** [comment]
Closing. User was using an outdated version of the mod.
