### ISSUE TITLE
Intimidating Officers with both Big Lobby and Better Bots Online crashing the game

### ISSUE THREAD

**Issue by Algester** [polarathene/biglobby#35]
http://pastebin.com/Lsu3BQc4
I'm not sure if this provides enough data to know which is conflicting who though

**Comment by polarathene** [comment]
Hi Algester, sounds like BigLobby just needs to sync to the latest PD2 update. I'll try sort that out for you shortly.

**Comment by polarathene** [comment]
@Algester please try [v2.38](https://github.com/polarathene/biglobby/releases/tag/v2.38), remember to update both the BLT mod and PDMOD files.

**Comment by Algester** [comment]
I will give feedback should I be able to start playing with biglobby

**Comment by Algester** [comment]
ok it works online without any hitches until overkill breaks it again with an update but until then I guess this ticket is closed
