### ISSUE TITLE
Client crashes when Little Friend 7.62 Assault Rifle (Grenade Attachment) is used in multiplayer lobbies

### ISSUE THREAD

**Issue by rockr230** [polarathene/biglobby#38]
I hope I posted the correct log.

Also crashes and produces the same crashlog when the Arbiter Grenade Launcher and Commando 101 Rocket Launcher are used.

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???

-------------------------------

Current thread: Main
Script stack:
                       throw()  lib/units/weapons/projectiles/projectilebase.lua:162
       sync_throw_projectile()  lib/units/weapons/projectiles/projectilebase.lua:185
                                lib/network/handlers/unitnetworkhandler.lua:2344

-------------------------------

System information:
    Application version : 1.68.209
    CPU : AMD A8-5500 APU with Radeon(tm) HD Graphics (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
    DirectX : 12.0 
    GPU : NVIDIA GeForce GTX 750 Ti / nvd3dum.dll[21.21.13.7653]
    Language : @ID94cca2fdaccfc2cd@
    Memory :     8117MB 296KB
    OS : 6.2.9200 () 0x300-0x1 (64 bits)
    Physics : threaded
    Renderer : DX9 threaded
    Sound : IDT (Speakers / Headphones (IDT High Definition Audio CODEC))

**Comment by polarathene** [comment]
Hi, thanks for the report! Seems I didn't update a value properly in a recent release, [this new release v.240](https://github.com/polarathene/biglobby/releases/tag/v2.40) should fix it for you :) Please try and let me know!

**Comment by rockr230** [comment]
Thanks for the the fix! I just tested it with a friend, and it works!
