### ISSUE TITLE
New update causes host to crash when client joins

### ISSUE THREAD

**Issue by rockr230** [polarathene/biglobby#40]
Payday 2 recently updated, so that might be the issue.

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        send()  lib/network/base/networkpeer.lua:1034               
                        send()  @mods/biglobby/lua/lib/network/base/_networkpeer.lua:14  
    on_join_request_received()  @mods/biglobby/lua/lib/network/base/session_states/_hoststateinlobby.lua:117  
    on_join_request_received()  lib/network/base/hostnetworksession.lua:55          
                                lib/network/base/handlers/connectionnetworkhandler.lua:50  

-------------------------------

**Comment by polarathene** [comment]
Hi @rockr230 , thanks for the report :) Please try [v2.41](https://github.com/polarathene/biglobby/releases/tag/v2.41) and let me know if it works for you.

**Comment by rockr230** [comment]
@polarathene , works! Thanks for the update!
