### ISSUE TITLE
New update causes host to crash when client tries to join

### ISSUE THREAD

**Issue by rockr230** [polarathene/biglobby#42]
Payday 2 updated again (new character pack)

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        send()  lib/network/base/networkpeer.lua:1034               
                        send()  @mods/biglobby/lua/lib/network/base/_networkpeer.lua:14  
    on_join_request_received()  @mods/biglobby/lua/lib/network/base/session_states/_hoststateinlobby.lua:117  
    on_join_request_received()  lib/network/base/hostnetworksession.lua:55          
                                lib/network/base/handlers/connectionnetworkhandler.lua:50  

-------------------------------

**Comment by polarathene** [comment]
@rockr230 Thanks for the report, please try [v2.42](https://github.com/polarathene/biglobby/releases/tag/v2.42) and let me know if it works :)

**Comment by rockr230** [comment]
@polarathene it works now! Thanks!
