### ISSUE TITLE
Error "Failed joining game"

### ISSUE THREAD

**Issue by RhysBaker** [polarathene/biglobby#45]
When big lobbies is turned on I always get the Error "Failed to join game" when trying to join a friend on steam who has the same mods installed and we both have the latest update. He also cannot join my lobby and gets the same error but other people can join his game with big lobbies .

When i turn just big lobbies off I can join games again but obviously cant join big lobby games.

I have tried re-installing the mods
re-installing the games
then re-installing the mods

**Comment by polarathene** [comment]
You both need same version of BLT and PDMOD mods. Current version is 2.43.

**Comment by RhysBaker** [comment]
Hi thanks for the response ill be sure to check it out when I can.
