### ISSUE TITLE
AI Name Problem

### ISSUE THREAD

**Issue by LuizBarros99** [polarathene/biglobby#46]
I have been getting a little problem with the Big Lobby mod, basically, with any lobby (in offline) above 4 players, my name gets duplicated, with one of my name being as normal, over/under my health circle, and one BOT(crew AI) gets its name replaced by my name. And my POCOHud stats, such as kills and downs, appear under the AI name that was replaced by my name. IDK what is causing it, but I run POCOHud, Better Bots, oviously the big lobby mod, the Additional Pocohud trackers, money in hud, and two assault waves mods, one state indicator, and one endless wave indicator. I also play on OFFLINE, any idea on how to fix it?﻿

**Comment by polarathene** [comment]
When raising an issue against BigLobby you should test with only BigLobby mod to know that it still happens with BigLobby alone. This issue appears to be due to an AI update in the game as described [here](https://github.com/polarathene/biglobby/issues/47).
