### ISSUE TITLE
[Game Updated] Mod is no longer working !

### ISSUE THREAD

**Issue by HKOLO** [polarathene/biglobby#54]
Big Lobby is not available any more as it updated last week on 29/6/2017.

[2017_07_06_log.txt](https://github.com/polarathene/biglobby/files/1125450/2017_07_06_log.txt)

Thank you for your help. <3

**Comment by polarathene** [comment]
@HKOLO Hi, I've pushed an update with the network method changes. Please give [v2.44](https://github.com/polarathene/biglobby/releases/tag/v2.44) a try and let me know if it works. Thanks.

**Comment by polarathene** [comment]
@HKOLO An update came not long after I release 2.44. It had lots of changes this time, you can try [v2.45](https://github.com/polarathene/biglobby/releases/tag/v2.45-peer-change-to-15) and let me know if it's working again? Thanks :)

**Comment by polarathene** [comment]
Others have confirmed the mod to be working now, closing this issue.
