### ISSUE TITLE
Update 150 causes Clients and Host crash when heist starts

### ISSUE THREAD

**Issue by rockr230** [polarathene/biglobby#57]
Update 150 introduced the new desync fix, so I think that might be breaking this mod
Crashlog:
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        send()  lib/network/base/networkpeer.lua:1041               
                        send()  @mods/biglobby/lua/lib/network/base/_networkpeer.lua:14  
                _send_queued()  lib/network/base/networkpeer.lua:1079               
            send_queued_sync()  lib/network/base/networkpeer.lua:1101               
       send_to_peers_synched()  lib/network/base/basenetworksession.lua:687         
                        send()  lib/network/base/extensions/networkbaseextension.lua:11  
         _get_max_walk_speed()  lib/units/beings/player/states/playerstandard.lua:1358  
            _update_movement()  lib/units/beings/player/states/playerstandard.lua:995  
                      update()  lib/units/beings/player/states/playerstandard.lua:421  
                                lib/units/beings/player/playermovement.lua:275

**Comment by WolfenGames** [comment]
Have this issue as well.


Crash date: 2017-07-06 09:05:06 PM

PAYDAY 2 Crash log
Application has crashed: access violation
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
-------------------------------
Current thread: Main
Script stack:
send()  lib/network/base/networkpeer.lua:1041               
_send_queued()  lib/network/base/networkpeer.lua:1079               
send_queued_sync()  lib/network/base/networkpeer.lua:1101               
send_to_peers_synched()  lib/network/base/basenetworksession.lua:687         
send()  lib/network/base/extensions/networkbaseextension.lua:11  
 _get_max_walk_speed()  lib/units/beings/player/states/playerstandard.lua:1358  
 _update_movement()  lib/units/beings/player/states/playerstandard.lua:995  
update_original()  lib/units/beings/player/states/playerstandard.lua:421                
lib/units/beings/player/playermovement.lua:275

**Comment by FVaeger** [comment]
Have you guys tried updating Big lobby mod or PDMods if its out of date if not idk if your joining someone without the mod then you need to to disable the blt mod

**Comment by rockr230** [comment]
@FVaeger Are you saying to update it ourselves, or to download the latest version of BigLobby? **I'm using the latest release** on here (https://github.com/polarathene/biglobby/releases/tag/v2.44), and I've tested it with a friend (**who also uses the latest version from here**), and **we still crash**. When we want to play **without the use of BigLobby**, we disable it, with no problems.

**Comment by FVaeger** [comment]
@rockr230 no I was just asking if that fixes your problem or not

**Comment by WolfenGames** [comment]
@FVaeger No it doesnt fix the problem

**Comment by polarathene** [comment]
@rockr230 @FVaeger @WolfenGames Hi guys. An update came not long after I release 2.44. It had lots of changes this time, you can try [v2.45](https://github.com/polarathene/biglobby/releases/tag/v2.45-peer-change-to-15) and let me know if it's working again? Thanks :)

**Comment by rockr230** [comment]
@polarathene It works! And my friend and I tested the issue with the First Aid Kits and Doctor Bags, and those work as well! Thanks!
