### ISSUE TITLE
New bug upon joining lobbies

### ISSUE THREAD

**Issue by WolfenGames** [polarathene/biglobby#58]
PAYDAY 2 Crash log
Application has crashed: access violation
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
-------------------------------
Current thread: Main
Script stack:
send()  lib/network/base/networkpeer.lua:1041               
send()  @mods/biglobby/lua/lib/network/base/_networkpeer.lua:14  
on_join_request_received()  @mods/biglobby/lua/lib/network/base/session_states/_hoststateinlobby.lua:117  
on_join_request_received()  lib/network/base/hostnetworksession.lua:55          
lib/network/base/handlers/connectionnetworkhandler.lua:50

**Comment by polarathene** [comment]
This is with v2.45 pdmod and BLT mods?

Your crash log suggests it's a network message problem. There doesn't seem to be any new network method changes, so I'm not sure what broke in the update. 

Make sure that both you and the other player who is hosting the lobby you joined both use the latest v2.45 pdmod and BLT mods.

**Comment by WolfenGames** [comment]
Yes, 2.45 and BLT. Happens when we try join each other. 
With fresh install

**Comment by polarathene** [comment]
Try do this change for me. 

- Find the file [biglobby/lua/lib/network/base/_networkpeer.lua](https://github.com/polarathene/biglobby/blob/master/biglobby/lua/lib/network/base/_networkpeer.lua) in the BLT mod.
- At line 10, add a new line and put this text after it `log("BL func_name: " .. func_name)`, alternatively can also try `BigLobbyGlobals:logger(func_name, false)`
- Save the file.

It should look like:

```Lua
if not BigLobbyGlobals:is_small_lobby() and BigLobbyGlobals.network_handler_funcs[func_name] then
    func_name = 'biglobby__' .. func_name
    log("BL func_name: " .. func_name)
end
```

Then run the game and trigger the crash. in the PD2 game folder you'll find `/mods/logs` and there should be one with recent date/time, open that up and search(ctrl+f) `BL func_name` The last one should be what was used before the crash. Could you share with me what that line was?

**Comment by WolfenGames** [comment]
Ok, it started working again when we tried it. I don't know what happened, I will remember this little bit of help for if I ever run into errors again.
