### ISSUE TITLE
Compatibility with new Lua?

### ISSUE THREAD

**Issue by tipakA** [polarathene/biglobby#61]
Last update changed Lua engine to LuaJIT, and I just wonder if it is compatible with it

**Comment by polarathene** [comment]
My advice would be to test, but there is another issue that suggests I need to push a sync update. I think I also have to check if is compatible with BLT 2.0. Right now I am a bit swamped with work

**Comment by polarathene** [comment]
Hi there sorry for the late response, I've been very busy working at a new startup company. Unfortunately I don't think I have the time to maintain this mod anymore for free. You can find a bounty link and more details in [this issue](https://github.com/polarathene/biglobby/issues/63) if you'd like to show some support to having the mod maintained.
