### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Crazynamehere** [polarathene/biglobby#62]
I have downloaded it and it is not showing up anywhere, I checked my mods and it says it's not compatible.

**Comment by polarathene** [comment]
Hi there sorry for the late response, I've been very busy working at a new startup company. Unfortunately I don't think I have the time to maintain this mod anymore for free. You can find a bounty link and more details in [this issue](https://github.com/polarathene/biglobby/issues/63) if you'd like to show some support to having the mod maintained.
